//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A8: return "Ignition 3";
		case Gpio::B12: return "Spare 2 Out";
		case Gpio::B13: return "Spare 1 Out";
		case Gpio::B7: return "Ignition 6";
		case Gpio::B9: return "Ignition 2";
		case Gpio::C13: return "Tacho Out";
		case Gpio::C6: return "Boost Out";
		case Gpio::C7: return "Idle 1 Out";
		case Gpio::D10: return "Ignition 4";
		case Gpio::D12: return "Injector 1";
		case Gpio::D13: return "Injector 2";
		case Gpio::D14: return "Injector 3";
		case Gpio::D15: return "Injector 4";
		case Gpio::D3: return "Idle 2 Out";
		case Gpio::D4: return "Flex Fuel Input";
		case Gpio::D7: return "Ignition 1";
		case Gpio::D9: return "Ignition 5";
		case Gpio::E0: return "VR/Hall 1";
		case Gpio::E1: return "VR/Hall 2";
		case Gpio::E11: return "Injector 6";
		case Gpio::E13: return "Injector 8";
		case Gpio::E14: return "Injector 7";
		case Gpio::E2: return "Idle Stepper EN";
		case Gpio::E3: return "Fuel Pump";
		case Gpio::E5: return "Idle Stepper STEP";
		case Gpio::E6: return "Fan";
		case Gpio::E7: return "Idle Stepper DIR";
		case Gpio::E9: return "Injector 5";
		default: return nullptr;
	}
	return nullptr;
}
