//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

#define PIN_5 E13
#define PIN_6 E14
#define PIN_7 E9
#define PIN_8 E11
#define PIN_9 C7
#define PIN_10 EFI_ADC_9
#define PIN_11 B12
#define PIN_12 B13
#define PIN_13 D7
#define PIN_14 EFI_ADC_4
#define PIN_15 E6
#define PIN_16 D3
#define PIN_17 EFI_ADC_10
#define PIN_18 EFI_ADC_0
#define PIN_19 E3
#define PIN_20 EFI_ADC_1
#define PIN_22 D9
#define PIN_23 EFI_ADC_14
#define PIN_24 D15
#define PIN_25 EFI_ADC_12
#define PIN_26 B7
#define PIN_27 EFI_ADC_13
#define PIN_28 D14
#define PIN_31 B9
#define PIN_32 D12
#define PIN_35 EFI_ADC_11
#define PIN_36 A8
#define PIN_38 D4
#define PIN_40 D10
#define PIN_44 D13
#define PIN_47 C6
#define PIN_48 C13
