//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::E13, // Injector 8
	Gpio::E14, // Injector 7
	Gpio::E9, // Injector 5
	Gpio::E11, // Injector 6
	Gpio::C7, // Idle 1 Out
	Gpio::B12, // Spare 2 Out
	Gpio::B13, // Spare 1 Out
	Gpio::E6, // Fan
	Gpio::D3, // Idle 2 Out
	Gpio::E3, // Fuel Pump
	Gpio::D15, // Injector 4
	Gpio::D14, // Injector 3
	Gpio::D12, // Injector 1
	Gpio::D13, // Injector 2
	Gpio::C6, // Boost Out
	Gpio::C13, // Tacho Out
	Gpio::E5, // Idle Stepper STEP
	Gpio::E7, // Idle Stepper DIR
	Gpio::E2, // Idle Stepper EN
	Gpio::D7, // Ignition 1
	Gpio::D9, // Ignition 5
	Gpio::B7, // Ignition 6
	Gpio::B9, // Ignition 2
	Gpio::A8, // Ignition 3
	Gpio::D10, // Ignition 4
// "Injector 8",
// "Injector 7",
// "Injector 5",
// "Injector 6",
// "Idle 1 Out",
// "Spare 2 Out",
// "Spare 1 Out",
// "Fan",
// "Idle 2 Out",
// "Fuel Pump",
// "Injector 4",
// "Injector 3",
// "Injector 1",
// "Injector 2",
// "Boost Out",
// "Tacho Out",
// "Idle Stepper STEP",
// "Idle Stepper DIR",
// "Idle Stepper EN",
// "Ignition 1",
// "Ignition 5",
// "Ignition 6",
// "Ignition 2",
// "Ignition 3",
// "Ignition 4",
}
