#
# See https://github.com/rusefi/rusefi/wiki/Connector-Mapping
#

name: Generate Interactive Pinouts

on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:
#  push:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate Pinouts
      uses: chuckwagoncomputing/interactive-pinout@2.15
      with:
        mapping-path: connectors/*.yaml
        warnings: "error"
        warning-dupe: "error"
        columns: |
          {
          "pin":"Pin Number",
          "ts_name":"TS Name",
          "type":"Type",
          "function":"Typical Function",
          "color":"Pigtail Color"
          }
        print-columns: |
          [
          "function"
          ]
        info-column: "type"
        colors: |
          {
          "12v":"yellow";
          "12V":"yellow";
          "5v":"red",
          "5V":"red",
          "at":"green",
          "av":"brown",
          "can":"blue",
          "din":"lime",
          "etb":"darkcyan",
          "gnd":"darkgreen",
          "gp_high":"aqua",
          "gp_low":"aquamarine",
          "gp_pp":"cyan",
          "hall":"darkolivegreen",
          "hl":"gold",
          "hs":"indigo",
          "ign":"magenta",
          "inj":"maroon",
          "ls":"lightgreen",
          "mr":"firebrick",
          "pgnd":"coral",
          "sgnd":"olive",
          "usb":"lightseagreen",
          "vr":"sienna"
          }

    - name: Showing Output Folder
      run: ls -l pinouts/

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: pinouts/spectre

  deploy:
    needs: generate
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
